### ISSUE TITLE
Verification fails with documentation defaults?

### ISSUE THREAD

**Issue by alexc-jeromes** [Spomky-Labs/otphp#202] opened 2024-01-10 03:07 UTC
### Version(s) affected

11.2.0

### Description

Using the defaults from the docs (https://github.com/Spomky-Labs/otphp/blob/11.3.x/doc/index.md), verification appears to fail with PHP 8.2.

```php
Psy Shell v0.11.22 (PHP 8.2.14 — cli) by Justin Hileman
> OTPHP\TOTP::createFromSecret('JBSWY3DPEHPK3PXP')->now()
= "380932"

> OTPHP\TOTP::createFromSecret('JBSWY3DPEHPK3PXP')->verify(380932);
= false

> OTPHP\TOTP::createFromSecret('JBSWY3DPEHPK3PXP')->verify('380932');
= false
```

### How to reproduce

See above. Tested in console, Laravel Tinker etc.

### Additional Context

Linux 887b63926a3e 5.15.133.1-microsoft-standard-WSL2 #1 SMP Thu Oct 5 21:02:42 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
PHP 8.2.14
Laravel 10.28.0

**Comment by Spomky** [comment] 2024-01-10 05:19
Hi,

I cannot reproduce. See https://phpsandbox.io/e/x/qhdca with the same calls.

**Comment by Spomky** [comment] 2024-04-14 16:41
Closing as no answer

**Closed as completed by Spomky** 2024-04-14 16:41 UTC
